-- Criação da Tabela de Categorias
CREATE TABLE [Categorias] (
[Id] INT PRIMARY KEY IDENTITY(1,1),
[Nome] NVARCHAR(100) NOT NULL
);

-- Criação da Tabela de Tarefas (Todos)
CREATE TABLE [Todos] (
[Id] INT PRIMARY KEY IDENTITY(1,1),
[Titulo] NVARCHAR(200) NOT NULL,
[Descricao] NVARCHAR(MAX),
[Concluido] BIT NOT NULL DEFAULT 0,
[CategoriaId] INT,
CONSTRAINT FK_Todos_Categorias FOREIGN KEY ([CategoriaId])
REFERENCES [Categorias]([Id]) ON DELETE SET NULL
);
